### PR TITLE
updated the plugin to the new build form and removed the git dependency

### PR DESCRIPTION
**Pull request by bvellacott**
Hi - I noticed I couldn't use this plugin with the latest version of broccoli so I updated the plugin to use the latest version of broccoli-caching-writer. Seemed to work fine :)

### CODE REVIEW

**Comment by GreatWizard** [comment]
I like what you did there!

**Comment by bvellacott** [comment]
cheers - have you taken the changes in - can I switch back to your original
npm repo?

B

2017-01-31 15:24 GMT+00:00 Guillaume Gérard <notifications@github.com>:

**Comment by GreatWizard** [comment]
AH sorry i'm not a maintainer of this addon :/
I'm just another developer who use this addon and would like to go on broccoli v1.x

But I hope the maintainer will merge it!

**Comment by GreatWizard** [comment]
If you want the pull request to be merge you should rollback some package modification about name, urls and homepage ;) else we will have some problems for the next release

**Comment by dustinfarris** [comment]
@Globegitter can this be merged?

**Comment by bvellacott** [comment]
Cool - me too


2017-02-04 11:34 GMT+00:00 Guillaume Gérard <notifications@github.com>:

**Comment by bvellacott** [comment]
Made the modifications as I didn't know if you were going to merge, and I needed the package, so was happy to maintain the branch. Will make the changes :)

**Comment by bvellacott** [comment]
@Globegitter - have a look at it now

**Comment by Globegitter** [comment]
@bvellacott thanks merged - I also gave you collaborator rights as I am not using broccoli myself anymore :)

**Comment by Globegitter** [comment]
Also if you give me your name on npm @bvellacott I can add you as an author there so you can push the update.

**Comment by GreatWizard** [comment]
Nice job guys, I'm waiting the release :)

**Comment by bvellacott** [comment]
@Globegitter - Benjamin Vellacott is the name - cheers

**Comment by bvellacott** [comment]
@Globegitter - have you switched to webpack?

**Comment by Globegitter** [comment]
@bvellacott Well changed directions quite a bit. Working more on the backend now. The company I am working for now is using webpack but personally not the biggest fan of what I have seen of it :)

**Comment by Globegitter** [comment]
Also can not find your profile on npmjs. Can you just send me the link? e.g. https://www.npmjs.com/~globegitter is the one to mine.

**Comment by bvellacott** [comment]
@Globegitter sure - https://www.npmjs.com/~bvellacott - I created a small project with webpack recently and was impressed by parts of it, but I don't know how it scales and I've been meaning to find out - what are your thoughts on webpack then ? - I wonder if I should put this in an email... :)

**Comment by dustinfarris** [comment]
I use Broccoli and (sometimes) webpack together.

https://github.com/myfreeweb/broccoli-webpack

**Comment by bvellacott** [comment]
@dustinfarris ok - that's something to consider - cheers

**Pull request merged**
