### PR TITLE
Fixes for browsersync options

### PR DESCRIPTION
**Pull request by mlaccetti**
Needed to get the broccoli-browser-sync stuff working to pass in middleware; please feel free to revert the package.json changes; I just needed to get it to NPM quickly.

### CODE REVIEW

**Comment by bekharsky** [comment]
Looks like this repository is abandoned :(

**Comment by mlaccetti** [comment]
Weird - @Globegitter is active on GitHub.  Maybe just a quick ping to let him know to come and look?  :)

**Comment by Globegitter** [comment]
@mlaccetti Sorry, just had some headspace for it now. Do you want push right and npm rights for this? Might be easier than me taking a year ;)

**Comment by mlaccetti** [comment]
@Globegitter sure, I'd be cool with getting this out for folks

**Comment by Globegitter** [comment]
Thanks. Added you to the repo and will add you to npm asap :)

**Comment by Globegitter** [comment]
@mlaccetti Added you to npm now as well.

**Comment by mlaccetti** [comment]
Deployed to `npm` earlier today.

**Pull request merged**
